// generated by tools/gen.py - do not edit
export const METRICS = {
  "480": {
    "bg": "bg.png",
    "ring_box": 440,
    "ring_frames": 20,
    "sec_w": 18,
    "sec_h": 186,
    "ring_r": 176.0,
    "big_w": 48,
    "big_h": 77,
    "date_w": 15,
    "date_h": 24,
    "date_dot_w": 10,
    "vit_w": 12,
    "vit_h": 20
  },
  "466": {
    "bg": "bg.png",
    "ring_box": 427,
    "ring_frames": 20,
    "sec_w": 17,
    "sec_h": 180,
    "ring_r": 170.86666666666667,
    "big_w": 47,
    "big_h": 74,
    "date_w": 15,
    "date_h": 22,
    "date_dot_w": 10,
    "vit_w": 12,
    "vit_h": 20
  }
}
export const LAYOUT = {
  "anchor": [
    333.26579050504404,
    90.74353507646904
  ],
  "elbow": [
    300,
    128
  ],
  "text_x": 104,
  "date_y": 101,
  "time_y": 136,
  "week_y": 222,
  "city_y": 250,
  "coord_y": 286,
  "bracket_bottom": 306,
  "vitals_y": 326,
  "vitals_label_y": 352,
  "vitals_x": [
    146,
    210,
    274,
    336
  ],
  "vitals_sep": [
    178,
    242,
    305
  ]
}
